### PR TITLE
DR docs

### PR DESCRIPTION
**Pull request by ody**

### CODE REVIEW

**Comment by ody** [comment]
Example scripts need retesting.

**Comment by ody** [comment]
Maybe move content entirely to docs folder too?

**Review by timidri — COMMENTED** [review]
@ody Any reason we are not using `pds-cli` for the GETs and POSTs?

Additionally, a question related to API design and unrelated to this PR: @reidmv @mcka1n did we make the API body object for POSTs different from the GET results on purpose? It would be easier if one could use the GET results directly for POSTs.

**Comment by ody** [comment]
@timidri Only reason I didn't use `pds-cli` is because the scope of the ticket was about documentation and I only wrote the scripts to validate the workflow worked. I proved that it does so i definitely feel we need a follow-up ticket for adding the backup/restore functionality directly to the CLI.

**Comment by ody** [comment]
@timidri Updated to use `pds-cli`. Procedure doesn't change.

**Review by timidri — APPROVED** [review]
LGTM

**Pull request merged**
