### PR TITLE
SOLARCH-789 added debian package creation and resolved bundler issues

### PR DESCRIPTION
**Pull request by davidsandilands**

### CODE REVIEW

**Comment by timidri** [comment]
@davidsandilands I have tested this on CentOS 7 / PE 2012.4.0 and get this error during service startup:
```
Feb 18 16:25:12 puppet systemd: Started Puppet Data Service server.
Feb 18 16:25:12 puppet puma: /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access': There was an error while trying to write to `/opt/puppetlabs/server/apps/pds-server/Gemfile.lock`. It is likely that you need to grant write permissions for that path. (Bundler::PermissionError)
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/shared_helpers.rb:102:in `filesystem_access'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/definition.rb:353:in `lock'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/runtime.rb:114:in `lock'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/runtime.rb:41:in `setup'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler.rb:149:in `setup'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1212:in `block (2 levels) in use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1211:in `block in use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1208:in `use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1447:in `<top (required)>'
Feb 18 16:25:12 puppet puma: from <internal:gem_prelude>:1:in `require'
Feb 18 16:25:12 puppet puma: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
Feb 18 16:25:12 puppet puma: /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/definition.rb:354:in `initialize': Permission denied @ rb_sysopen - /opt/puppetlabs/server/apps/pds-server/Gemfile.lock (Errno::EACCES)
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/definition.rb:354:in `open'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/definition.rb:354:in `block in lock'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/shared_helpers.rb:103:in `filesystem_access'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/definition.rb:353:in `lock'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/runtime.rb:114:in `lock'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/runtime.rb:41:in `setup'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler.rb:149:in `setup'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1212:in `block (2 levels) in use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1211:in `block in use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems/user_interaction.rb:47:in `use_ui'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1208:in `use_gemdeps'
Feb 18 16:25:12 puppet puma: from /opt/puppetlabs/puppet/lib/ruby/2.7.0/rubygems.rb:1447:in `<top (required)>'
Feb 18 16:25:12 puppet puma: from <internal:gem_prelude>:1:in `require'
Feb 18 16:25:12 puppet puma: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
Feb 18 16:25:12 puppet systemd: pds-server.service: main process exited, code=exited, status=1/FAILURE
Feb 18 16:25:12 puppet systemd: Unit pds-server.service entered failed state.
Feb 18 16:25:12 puppet systemd: pds-server.service failed.
Feb 18 16:25:13 puppet systemd: pds-server.service holdoff time over, scheduling restart.
Feb 18 16:25:13 puppet systemd: Stopped Puppet Data Service server.
Feb 18 16:25:13 puppet systemd: start request repeated too quickly for pds-server.service
Feb 18 16:25:13 puppet systemd: Failed to start Puppet Data Service server.
Feb 18 16:25:13 puppet systemd: Unit pds-server.service entered failed state.
Feb 18 16:25:13 puppet systemd: pds-server.service failed.
Feb 18 16:25:13 puppet systemd: Removed slice User Slice of root.
```

**Comment by davidsandilands** [comment]
Interesting @timidri will just get one up my rhel 8 and ubuntus seems to be ok wonder why rhel 7 is being different

**Comment by davidsandilands** [comment]
@timidri what is in /usr/lib/systemd/system/pds-server.service for execstart it should be something like

/opt/puppetlabs/server/apps/pds-server/vendor/bundle/ruby/<%= ruby_version %>/bin/puma -C config/puma.rb -e production

**Comment by timidri** [comment]
> @timidri what is in /usr/lib/systemd/system/pds-server.service for execstart it should be something like
> 
> /opt/puppetlabs/server/apps/pds-server/vendor/bundle/ruby/<%= ruby_version %>/bin/puma -C config/puma.rb -e production

@davidsandilands This is my unit file: 
```
[Unit]
Description=Puppet Data Service server
After=network.target

[Service]
Type=simple
User=pds-server
WorkingDirectory=/opt/puppetlabs/server/apps/pds-server
Environment=RUBYOPT=-r/opt/puppetlabs/server/apps/pds-server/vendor/bundle/bundler/setup.rb
Environment=RUBYGEMS_GEMDEPS=/opt/puppetlabs/server/apps/pds-server/Gemfile
Environment=PATH=/opt/puppetlabs/puppet/bin:$PATH
Environment=GEM_PATH=/opt/puppetlabs/server/apps/pds-server/vendor/bundle/ruby/2.7.0/
ExecStart=/opt/puppetlabs/server/apps/pds-server/vendor/bundle/ruby/2.7.0/bin/puma -C config/puma.rb -e production
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by davidsandilands** [comment]
@timidri unable to replicate in centos7 in azure what image / cloud you using? Not an SE linux type thing is it?

**Comment by timidri** [comment]
> @timidri unable to replicate in centos7 in azure what image / cloud you using? Not an SE linux type thing is it?

I think the question is why the startup process wants to write to that file. The fact that it cannot is easily explained by the fact that files are owned by `root` but the service is running as user `pds-server`.

**Comment by davidsandilands** [comment]
@timidri I think i have resolved this issue by adding the platform as per latest commit https://github.com/puppetlabs/puppet-data-service/blob/SOLARCH-789-rebase/Makefile#L102

**Review by timidri — APPROVED** [review]
LGTM - tested on 2019.8.10 and 2021.5.0 and it works both with manual and module installation.

**Pull request merged**
