### PR TITLE
Workflow for building and releaseing packages

### PR DESCRIPTION
**Pull request by ody**
Introduces a workflow that when provided an array of PE versions will
generate a GitHub release for the version number found in the VERSION
file and upload to that release a package for each PE version provided.

### CODE REVIEW

**Comment by ody** [comment]
There were a couple other iterations of this that used other actions which were actively maintained but the originals provided by Github worked better when I introduced a matrix. Tried extended matric to each operating system version but matrix is not available when defining the step's action via the `uses` field.

**Comment by ody** [comment]
Side effect of the use of matrix is that when running the workflow you must set the input parameter as simple json.

*Example*
`["2021.4.0", "2019.8.10"]`

**Comment by ody** [comment]
JSON inputs and on push do not seem to work well together so new commit which triggers on tag removes `fromJSON`.

**Review by timidri — COMMENTED** [review]
@ody I don't seem to find how the VERSION file gets created. That should use the tag value, right?

**Comment by ody** [comment]
@timidri I created that VERSION file in the first commit, when the workflow was triggered manually. I needed it out of the Makefile so I could easily use it as the source version for the release, that process subsequently also created a tag that corresponded to the version.

In the second commit where I convert this to being triggered on creation of a new tag, the tag defines the release version so the VERSION file is not strictly required and the version which the package creation process uses could revert back to the Makefile as the source of truth.

...but it does make me think of another workflow we could evaluate

1. Push tag of v0.1.1
2. New tag triggers workflow to create release
3. 0.1.1 is written to the runner's VERSION file in its checkout of the code
4. Packages are built with intended version
5. Packages are added to the release
6. Workflow creates a PR to update upstream repository's copy of VERSION to something akin to 0.1.2-dev so packages built by hand always have a newer version number

**Comment by reidmv** [comment]
I think a preferred workflow would be to trigger the release workflow, and that the workflow should automatically tag and create the release. Having the entry point be the workflow, rather than a tagging option, keeps the door open for "releasing" to make further automated changes and commits, such as generating a changelog, modifying the VERSION from to remove the "*-dev" component for a release commit, tag that, and make a post-release commit that updates the version to a new "*-dev" value, etc.

We lose out on the option to add that kind of automation if we rely on humans to set the tag on a specific commit.

**Comment by ody** [comment]
@reidmv The workflow you describe is more like the first commit. I converted it to be triggered off the tag creation in the second commit because that is what was described in the outcome of SOLARCH-808.

The original commit used a `workflow_dispatch` event and took a version input parameter of PE versions, package version was sourced from `VERSION` file. Full release workflow required that the `VERSION` file be updated through an explicit pre-release commit with an update to the desired version number before running the workflow and the workflow would generate the tag, release, and upload packages.

I have no strong opinion of which we choose. I built it like I did in the first commit because it was similar to what had been implemented for PEADM but rebuilt it to be based off tag after re-reading the ticket when putting it into the review state. If I was forced to choose I'd simply default to precedence, selecting something similar to PEADM.

**Comment by reidmv** [comment]
Ah, I see that. Yeah. I think in this case, 808 is in error. The release should create the tag, not vise versa.

**Comment by ody** [comment]
I'll pushed a new version of this which is triggered manually but now also asks for a version to release and commits the new version to repository. Short demo here: https://youtu.be/kF8q0YpFYSM

**Review by reidmv — APPROVED** [review]
LGTM! 👍 

This is a great foundation @ody! We can keep building on it if we want to. As-is, this gives us the "Release" button we need to start with. 🎉

**Comment by timidri** [comment]
@ody this looks awesome, including the video!

**Pull request merged**
